---
# tasks file for bf2-installer-role
- name: "Create usergroup"
  ansible.builtin.group:
    name: "{{ bf2_user }}"
  become: true

- name: "Create user {{ bf2_user }}"
  ansible.builtin.user:
    create_home: true
    name: "{{ bf2_user }}"
    password: "{{ bf2_user_prompted_pw | password_hash('sha512') }}"
  become: true

- name: "Create dir for core bf2Serverfiles to upload"
  ansible.builtin.file:
    path: "{{ bf2_server_filesdir }}"
    state: directory
    owner: "{{ bf2_user }}"
    group: "{{ bf2_user }}"
  become: true
    
- name: "Create dir for core bf2SandboxServerfiles to upload"
  ansible.builtin.file:
    path: "{{ bf2sbx_server_filesdir }}"
    state: directory
    owner: "{{ bf2_user }}"
    group: "{{ bf2_user }}"
  become: true

- name: "Create dir for the bf2SBX server home"
  ansible.builtin.file:
    path: "{{ bf2sbx_server_home }}"
    state: directory
    owner: "{{ bf2_user }}"
    group: "{{ bf2_user }}"
  become: true
    
- name: "Upload bf2 serverfiles"
  ansible.builtin.copy:
    src: "../files/{{ bf2_serverfilename }}"
    dest: "{{ bf2_server_filesdir }}"
    owner: "{{ bf2_user }}"
    group: "{{ bf2_user }}"
  become: true

- name: "Upload sandbox serverfiles"
  ansible.builtin.copy:
    src: ../files/{{ bf2sbx_serverfilename }}
    dest: "{{ bf2sbx_server_filesdir }}"
    group: "{{ bf2_user }}"
    owner: "{{ bf2_user }}"
  become: true
  
- name: "Decompress bf2 Serverfiles from {{ bf2_server_filesdir }}/{{ bf2_serverfilename }} into {{ bf2sbx_server_home }} directory. This will install the bf2 server"
  ansible.builtin.unarchive:
    group: "{{ bf2_user }}"
    owner: "{{ bf2_user }}"
    remote_src: true
    src: "{{ bf2_server_filesdir }}/{{ bf2_serverfilename }}"
    dest: "{{ bf2sbx_server_home }}"
    extra_opts:
    - '-z'
    #-z needed because it is a tar.gz file
  become: true

- name: "Decompress sandbox Serverfiles from {{ bf2sbx_server_filesdir }}/{{ bf2sbx_serverfilename }} into {{ bf2sbx_mod_home }} directory. This will install the sandbox mod into the existing bf2 server"
  ansible.builtin.unarchive:
    group: "{{ bf2_user }}"
    owner: "{{ bf2_user }}"
    remote_src: true
    src: "{{ bf2sbx_server_filesdir }}/{{ bf2sbx_serverfilename }}"
    dest: "{{ bf2sbx_mod_home }}"
  become: true

#TODO: Implement me
  #- name: "Change IP of sbxNetwork server to use for @netsavegroup and @netloadgroup
  "







