---
# tasks file for bf2-installer-role
- name: "Create usergroup"
  ansible.builtin.group:
    name: "{{ bf2_user }}"
  become: true

- name: "Create user {{ bf2_user }}"
  ansible.builtin.user:
    create_home: true
    name: "{{ bf2_user }}"
    password: "{{ bf2_user_prompted_pw | password_hash('sha512') }}"
  become: true

- name: "Create dir for core bf2Serverfiles to upload"
  ansible.builtin.file:
    path: "{{ bf2_server_filesdir }}"
    state: directory
    owner: "{{ bf2_user }}"
    group: "{{ bf2_user }}"
    
- name: "Create dir for core bf2SandboxServerfiles to upload"
  ansible.builtin.file:
    path: "{{ bf2sbx_server_filesdir }}"
    state: directory
    owner: "{{ bf2_user }}"
    group: "{{ bf2_user }}"

- name: "Create dir for the bf2SBX server home"
  ansible.builtin.file:
    path: "{{ bf2sbx_server_home }}"
    state: directory
    owner: "{{ bf2_user }}"
    group: "{{ bf2_user }}"
    
- name: "Upload bf2 serverfiles"
  ansible.builtin.copy:
    src: "../files/battlefield2_linux_server_1.5.3153.0.tar.gz"
    dest: "{{ bf2_server_filesdir }}"
    owner: "{{ bf2_user }}"
    group: "{{ bf2_user }}"

- name: "Upload sandbox serverfiles"
  ansible.builtin.copy:
    src: ../files/sandbox_server_1.0.1.zip
    dest: "{{ bf2sbx_server_filesdir }}"
    group: "{{ bf2_user }}"
    owner: "{{ bf2_user }}"

- name: "Decompress bf2 Serverfiles into {{ bf2sbx_server_home }} directory. This will install the bf2 server"
  ansible.builtin.unarchive:
    group: "{{ bf2_user }}"
    owner: "{{ bf2_user }}"
    remote_src: true
    src: "{{ bf2_server_filesdir }}"
    dest: "{{ bf2sbx_server_home }}"

- name: "Decompress sandbox Serverfiles into {{ bf2sbx_mod_home }} directory. This will install the sandbox mod into the existing bf2 server"
  ansible.builtin.unarchive:
    group: "{{ bf2_user }}"
    owner: "{{ bf2_user }}"
    remote_src: true
    src: "{{ bf2_server_filesdir }}"
    dest: "{{ bf2sbx_mod_home }}"

# TODO: 
#   install python3 on the system (own file) (newest) (!NOT IDEMPOTET!)
#   install pip on the system (newest) (!NOT IDEMPOTET!)
#   install python3-apt to use the apt module (own file) 
#   install screen using apt
#   install bf2hub files https://www.bf2hub.com/home/serversetup.php
#   add to users crontab:
#     @reboot @reboot sleep20; cd /home/bf2/sandbox/bf2 && /usr/bin/screen -L -A -m -d -S bf2sbx ./start.sh +modPath mods/sandbox
#     */5 * * * * /home/bf2/sandbox/scripts/checkServerRunning.sh
#   




