---
# tasks file for install_screen

- name: "Installing screen on System Message"
  ansible.builtin.debug:
    msg: "installing Screen on {{ ansible_hostname }}"

- name: "Install screen"
  ansible.builtin.package:
    name: "screen"
  become: true

- name: "install git"
  ansible.builtin.package:
    name: "git"
  become: true