- name: "Preperate saveandload folder"
  ansible.builtin.file: 
    path: "/home/{{ tomcat_linuxuser }}/saveandloadserver"
    state: directory
    owner: "{{ tomcat_linuxuser }}"
    group: "{{ tomcat_linuxuser }}"
  become: true

- name: "Download saveandload .war file into {{ tomcat_webapps_folder }}"
  ansible.builtin.get_url:
    dest: "{{ tomcat_webapps_folder }}"
    url: "{{ saveandload_git_url }}"
    owner: "{{ tomcat_linuxuser }}"
    group: "{{ tomcat_linuxuser }}"
  become: true

