---
    
- name: "Preperate Java folders"
  ansible.builtin.file: 
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  loop:
    - { path: '{{ java_home }}', owner: '{{ java_home_folderowner }}', group: '{{ java_home_foldergroup }}' }
    - { path: "/home/{{ tomcat_linuxuser }}/javaTarBall", owner: {{ tomcat_linuxuser }}, group: {{ tomcat_linuxuser }} }
  become: true

- name: "Download Java TarBall"
  ansible.builtin.get_url:
    dest: "/home/{{ tomcat_linuxuser }}/javaTarBall"
    url: "{{ java_jdk_downloadlink }}"
    owner: "{{ tomcat_linuxuser }}"
    group: "{{ tomcat_linuxuser }}"
  become: true

- name: "Unpack Java files from Java TarBall"
  ansible.builtin.unarchive:
    remote_src: true
    owner: "{{ java_home_folderowner }}"
    group: "{{ java_home_foldergroup }}"
    dest: "{{ java_home }}"
    src: "/home/{{ tomcat_linuxuser }}/javaTarBall"
    extra_opts: [--strip-components=1]
  become: true

- name: "Adding java-paths to path"
  lineinfile:
    dest: "/etc/environment"
    state: "present"
    backrefs: yes
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop: 
    - { regexp: 'PATH=(["]*)((?!.*?{{ java_bin_path }}).*?)(["]*)$', line: "PATH=\1\2:{{ java_bin_path }}\3"}
    - { regexp: 'PATH=(["]*)((?!.*?{{ java_db_bin_path }}).*?)(["]*)$', line: "PATH=\1\2:{{ java_db_bin_path }}\3"} 
  become: true

- name: "Add {{ java_home }} as JAVA_HOME to environment variables"
  ansible.builtin.lineinfile:
    backup: true
    state: present
    line: "JAVA_HOME={{ java_home | quote }}"
    insertbefore: BOF
  become: true
- 